# Generated by Django 5.2.4 on 2025-07-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
