# Generated by Django 5.2.4 on 2025-07-18 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0002_alter_myuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=25)),
                ('branch_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('ntn', models.CharField(blank=True, max_length=50, null=True)),
                ('strn', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.BinaryField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditorDebitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_title', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiabilityDisposePriority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LiabilityName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiabilityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainLiability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('liability_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('liability_type', models.CharField(max_length=100)),
                ('dispose_priority', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('fiscal_year', models.CharField(default='2025-2026', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_no', models.CharField(max_length=25)),
                ('account_title', models.CharField(default='', max_length=255)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('is_active', models.BooleanField()),
                ('is_default', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liabilities.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liabilities.company')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liabilities.company'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_no', models.CharField(max_length=25)),
                ('account_title', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('mode_of_payment', models.CharField(choices=[('online', 'Online'), ('atm', 'ATM'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='online', max_length=10)),
                ('transaction_no', models.CharField(max_length=50)),
                ('transaction_remarks', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fiscal_year', models.CharField(default='2025-2026', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liabilities.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liabilities.company')),
                ('creditor_debitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='liabilities.creditordebitor')),
            ],
        ),
    ]
